version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}

  backend:
    build:
      context: ./back/spe-con
      dockerfile: Dockerfile.${RAILS_ENV}
    volumes:
      - ./back/spe-con:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${USER}:${PASSWORD}@db/${DB}
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./front/spe-con
      dockerfile: Dockerfile
    volumes:
      - ./front/spe-con:/app
      - /app/node_modules
    ports:
      - "8000:3000"
    command: npm run dev

volumes:
  postgres_data:
